CARDTYPE = ["Action", "Reaction", "Attack", "Victory",
            "Treasure", "Duration", "Looter", "Reserve",
            "Traveller", "Gathering", "Night", "Fate", "Doom"]

GAMEEDITIONS = ["Dominion",
                "Dominion 1st Edition",
                "Dominion 2nd Edition",
                "Intrigue",
                "Intrigue 1st Edition",
                "Intrigue 2nd Edition",
                "Seaside",
                "Alchemy",
                "Prosperity",
                "Cornucopia",
                "Hinterlands",
                "Dark Ages",
                "Guilds",
                "Adventures",
                "Empires",
                "Nocturne",
                "Renaissance",
                "Menagerie"]

COST = ["Potion", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]

KINGDOMCARDDECK = [['Title', 'Cost', 'Type', 'Edition'],
                   ['Cellar', '[Two]', '[Action]', 'Dominion'],
                   ['Chapel', '[Two]', '[Action]', 'Dominion'],
                   ['Moat', '[Two]', '[Reaction]', 'Dominion'],
                   ['Village', '[Three]', '[Action]', 'Dominion'],
                   ['Workshop', '[Three]', '[Action]', 'Dominion'],
                   ['Bureaucrat', '[Four]', '[Attack]', 'Dominion'],
                   ['Gardens', '[Four]', '[Victory]', 'Dominion'],
                   ['Militia', '[Four]', '[Attack]', 'Dominion'],
                   ['Moneylender', '[Four]', '[Action]', 'Dominion'],
                   ['Remodel', '[Four]', '[Action]', 'Dominion'],
                   ['Smithy', '[Four]', '[Action]', 'Dominion'],
                   ['Throne Room', '[Four]', '[Action]', 'Dominion'],
                   ['Council Room', '[Five]', '[Action]', 'Dominion'],
                   ['Festival', '[Five]', '[Action]', 'Dominion'],
                   ['Laboratory', '[Five]', '[Action]', 'Dominion'],
                   ['Library', '[Five]', '[Action]', 'Dominion'],
                   ['Market', '[Five]', '[Action]', 'Dominion'],
                   ['Mine', '[Five]', '[Action]', 'Dominion'],
                   ['Witch', '[Five]', '[Attack]', 'Dominion'],
                   ['Merchant', '[Three]', '[Action]', 'Dominion 2nd Edition'],
                   ['Vassal', '[Three]', '[Action]', 'Dominion 2nd Edition'],
                   ['Poacher', '[Four]', '[Action]', 'Dominion 2nd Edition'],
                   ['Bandit', '[Four]', '[Attack]', 'Dominion 2nd Edition'],
                   ['Sentry', '[Four]', '[Attack]', 'Dominion 2nd Edition'],
                   ['Artisan', '[Six]', '[Action]', 'Dominion 2nd Edition'],
                   ['Chancellor', '[Three]', '[Action]', 'Dominion 1st Edition'],
                   ['Woodcutter', '[Three]', '[Action]', 'Dominion 1st Edition'],
                   ['Feast', '[Four]', '[Action]', 'Dominion 1st Edition'],
                   ['Spy', '[Four]', '[Attack]', 'Dominion 1st Edition'],
                   ['Thief', '[Four]', '[Attack]', 'Dominion 1st Edition'],
                   ['Adventurer', '[Six]', '[Action]', 'Dominion 1st Edition'],
                   ['Courtyard', '[Two]', '[Action]', 'Intrigue'],
                   ['Pawn', '[Two]','[Action]', 'Intrigue'],
                   ['Masquerade', '[Three]', '[Action]', 'Intrigue'],
                   ['Shanty Town', '[Three]', '[Action]', 'Intrigue'],
                   ['Steward', '[Three]', '[Action]', 'Intrigue'],
                   ['Swindler', '[Three]', '[Attack]', 'Intrigue'],
                   ['Wishing Well', '[Three]', '[Action]', 'Intrigue'],
                   ['Baron', '[Four]', '[Action]', 'Intrigue'],
                   ['Bridge', '[Four]', '[Action]', 'Intrigue'],
                   ['Conspirator', '[Four]', '[Action]', 'Intrigue'],
                   ['Ironworks', '[Four]', '[Action]', 'Intrigue'],
                   ['Mining Village', '[Four]', '[Action]', 'Intrigue'],
                   ['Duke', '[Five]', '[Victory]', 'Intrigue'],
                   ['Minion', '[Five]', '[Attack]', 'Intrigue'],
                   ['Torturer', '[Five]', '[Attack]', 'Intrigue'],
                   ['Trading Post', '[Five]', '[Action]', 'Intrigue'],
                   ['Upgrade', '[Five]', '[Action]', 'Intrigue'],
                   ['Harem', '[Six]', '[Victory/Treasure]', 'Intrigue'],
                   ['Nobles', '[Six]', '[Action/Victory]', 'Intrigue'],
                   ['Secret Chamber', '[Two]', '[Reaction]', 'Intrigue 1st Edition'],
                   ['Great Hall', '[Three]', '[Action/Victory]', 'Intrigue 1st Edition'],
                   ['Coppersmith', '[Four]', '[Action]', 'Intrigue 1st Edition'],
                   ['Scout', '[Four]', '[Action]', 'Intrigue 1st Edition'],
                   ['Saboteur', '[Five]', '[Attack]', 'Intrigue 1st Edition'],
                   ['Tribute', '[Five]', '[Action]', 'Intrigue 1st Edition'],
                   ['Lurker', '[Two]', '[Action]', 'Intrigue 2nd Edition'],
                   ['Diplomat', '[Four]', '[Reaction]', 'Intrigue 2nd Edition'],
                   ['Mill', '[Four]', '[Action/Victory]', 'Intrigue 2nd Edition'],
                   ['Secret Passage', '[Three]', '[Action]', 'Intrigue 2nd Edition'],
                   ['Courtier', '[Five]', '[Action]', 'Intrigue 2nd Edition'],
                   ['Patrol', '[Five]', '[Action]', 'Intrigue 2nd Edition'],
                   ['Replace', '[Five]', '[Attack]', 'Intrigue 2nd Edition'],
                   ['Embargo', '[Two]', '[Action]', 'Seaside'],
                   ['Haven', '[Two]', '[Duration]', 'Seaside'],
                   ['Lighthouse', '[Two]', '[Duration]', 'Seaside'],
                   ['Native Village', '[Two]', '[Action]', 'Seaside'],
                   ['Pearl Diver', '[Two]', '[Action]', 'Seaside'],
                   ['Ambassador', '[Two]', '[Attack]', 'Seaside'],
                   ['Fishing Village', '[Three]', '[Duration]', 'Seaside'],
                   ['Lookout', '[Three]', '[Action]', 'Seaside'],
                   ['Smugglers', '[Three]', '[Action]', 'Seaside'],
                   ['Warehouse', '[Three]', '[Action]', 'Seaside'],
                   ['Caravan', '[Four]', '[Duration]', 'Seaside'],
                   ['Cutpurse', '[Four]', '[Attack]', 'Seaside'],
                   ['Island', '[Four]', '[Action/Victory]', 'Seaside'],
                   ['Pirate Ship', '[Four]', '[Attack]', 'Seaside'],
                   ['Salvager', '[Four]', '[Action]', 'Seaside'],
                   ['Sea Hag', '[Four]', '[Attack]', 'Seaside'],
                   ['Treasure Map', '[Four]', '[Action]', 'Seaside'],
                   ['Bazaar', '[Five]', '[Action]', 'Seaside'],
                   ['Explorer', '[Five]', '[Action]', 'Seaside'],
                   ['Ghost Ship', '[Five]', '[Attack]', 'Seaside'],
                   ['Merchant Ship', '[Five]', '[Duration]','Seaside'],
                   ['Outpost', '[Five]', '[Duration]', 'Seaside'],
                   ['Tactician', '[Five]', '[Duration]', 'Seaside'],
                   ['Treasury', '[Five]', '[Action]', 'Seaside'],
                   ['Wharf', '[Five]', '[Duration]', 'Seaside'],
                   ['Transmute', '[Potion]', '[Action]', 'Alchemy'],
                   ['Vineyard', '[Potion]', '[Victory]', 'Alchemy'],
                   ['Herbalist', '[Two]', '[Action]', 'Alchemy'],
                   ['Apothecary', '[Potion/Two]', '[Action]', 'Alchemy'],
                   ['Scrying Pool', '[Potion/Two]', '[Attack]', 'Alchemy'],
                   ['University', '[Potion/Two]', '[Action]', 'Alchemy'],
                   ['Alchemist', '[Potion/Three]', '[Action]', 'Alchemy'],
                   ['Familiar', '[Potion/Three]', '[Attack]', 'Alchemy'],
                   ["Philosopher's Stone", '[Potion/Three]', '[Treasure]', 'Alchemy'],
                   ['Golem', '[Potion/Four]', '[Action]', 'Alchemy'],
                   ['Apprentice', '[Five]', '[Action]', 'Alchemy'],
                   ['Possession', '[Potion/Six]', '[Action]', 'Alchemy'],
                   ['Loan', '[Three]', '[Treasure]', 'Prosperity'],
                   ['Trade Route', '[Three]', '[Action]', 'Prosperity'],
                   ['Watchtower', '[Three]', '[Reaction]', 'Prosperity'],
                   ['Bishop', '[Four]', '[Action]', 'Prosperity'],
                   ['Monument', '[Four]', '[Action]', 'Prosperity'],
                   ['Quarry', '[Four]', '[Treasure]', 'Prosperity'],
                   ['Talisman', '[Four]', '[Treasure]', 'Prosperity'],
                   ["Worker's Village", '[Four]', '[Action]', 'Prosperity'],
                   ['City', '[Five]', '[Action]', 'Prosperity'],
                   ['Contraband', '[Five]', '[Treasure]', 'Prosperity'],
                   ['Counting House', '[Five]', '[Action]', 'Prosperity'],
                   ['Mint', '[Five]', '[Action]', 'Prosperity'],
                   ['Mountebank', '[Five]', '[Attack]', 'Prosperity'],
                   ['Rabble', '[Five]', '[Attack]', 'Prosperity'],
                   ['Royal Seal', '[Five]', '[Treasure]', 'Prosperity'],
                   ['Vault', '[Five]', '[Action]', 'Prosperity'],
                   ['Venture', '[Five]', '[Treasure]', 'Prosperity'],
                   ['Goons', '[Six]', '[Attack]', 'Prosperity'],
                   ['Grand Market', '[Six]', '[Action]', 'Prosperity'],
                   ['Hoard', '[Six]', '[Treasure]', 'Prosperity'],
                   ['Bank', '[Seven]', '[Treasure]', 'Prosperity'],
                   ['Expand', '[Seven]', '[Action]', 'Prosperity'],
                   ['Forge', '[Seven]', '[Action]', 'Prosperity'],
                   ["King's Court", '[Seven]', '[Action]', 'Prosperity'],
                   ['Peddler', '[Eight]', '[Action]', 'Prosperity'],
                   ['Hamlet', '[Two]', '[Action]', 'Cornucopia'],
                   ['Fortune Teller', '[Three]', '[Attack]', 'Cornucopia'],
                   ['Menagerie', '[Three]', '[Action]', 'Cornucopia'],
                   ['Farming Village', '[Four]', '[Action]', 'Cornucopia'],
                   ['Horse Traders', '[Four]', '[Reaction]', 'Cornucopia'],
                   ['Remake', '[Four]', '[Action]', 'Cornucopia'],
                   ['Tournament', '[Four]', '[Action]', 'Cornucopia'],
                   ['Young Witch', '[Four]', '[Attack]', 'Cornucopia'],
                   ['Harvet', '[Five]', '[Action]', 'Cornucopia'],
                   ['Horn of Plenty', '[Five]', '[Treasure]', 'Cornucopia'],
                   ['Hunting Party', '[Five]', '[Action]','Cornucopia'],
                   ['Jester', '[Five]', '[Attack]', 'Cornucopia'],
                   ['Fairgrounds', '[Six]', '[Victory]', 'Cornucopia'],
                   ['Crossroads', '[Two]', '[Action]', 'Hinterlands'],
                   ['Duchess', '[Two]', '[Action]', 'Hinterlands'],
                   ["Fool's Gold", '[Two]', '[Reaction/Treasure]', 'Hinterlands'],
                   ['Develop', '[Three]', '[Action]', 'Hinterlands'],
                   ['Oasis', '[Three]', '[Action]', 'Hinterlands'],
                   ['Oracle', '[Three]', '[Attack]', 'Hinterlands'],
                   ['Scheme', '[Three]', '[Action]', 'Hinterlands'],
                   ['Tunnel', '[Three]', '[Reaction/Victory]', 'Hinterlands'],
                   ['Jack Of All Trades', '[Four]', '[Action]', 'Hinterlands'],
                   ['Noble Brigand', '[Four]', '[Attack]', 'Hinterlands'],
                   ['Nomad Camp', '[Four]', '[Action]', 'Hinterlands'],
                   ['Silk Road', '[Four]', '[Victory]', 'Hinterlands'],
                   ['Spice Merchant', '[Four]', '[Action]', 'Hinterlands'],
                   ['Trader', '[Four]', '[Reaction]', 'Hinterlands'],
                   ['Cache', '[Five]', '[Treasure]', 'Hinterlands'],
                   ['Cartographer', '[Five]', '[Action]', 'Hinterlands'],
                   ['Embassy', '[Five]', '[Action]', 'Hinterlands'],
                   ['Haggler', '[Five]', '[Action]', 'Hinterlands'],
                   ['Highway', '[Five]', '[Action]', 'Hinterlands'],
                   ['Ill Gotten Gains', '[Five]', '[Treasure]', 'Hinterlands'],
                   ['Inn', '[Five]', '[Action]', 'Hinterlands'],
                   ['Mandarin', '[Five]', '[Action]', 'Hinterlands'],
                   ['Margrave', '[Five]', '[Attack]', 'Hinterlands'],
                   ['Stables', '[Five]', '[Action]', 'Hinterlands'],
                   ['Border Village', '[Six]', '[Action]', 'Hinterlands'],
                   ['Farmland', '[Six]', '[Victory]', 'Hinterlands'],
                   ['Poor House', '[One]', '[Action]', 'Dark Ages'],
                   ['Begger', '[Two]', '[Reaction]', 'Dark Ages'],
                   ['Squire', '[Two]', '[Action]', 'Dark Ages'],
                   ['Vagrant', '[Two]', '[Action]', 'Dark Ages'],
                   ['Forager', '[Three]', '[Action]', 'Dark Ages'],
                   ['Hermit', '[Three]', '[Action]', 'Dark Ages'],
                   ['Market Square', '[Three]', '[Reaction]', 'Dark Ages'],
                   ['Sage', '[Three]', '[Action]', 'Dark Ages'],
                   ['Storeroom', '[Three]', '[Action]', 'Dark Ages'],
                   ['Urchin', '[Three]', '[Attack]', 'Dark Ages'],
                   ['Armory', '[Four]', '[Action]','Dark Ages'],
                   ['Death Cart', '[Four]', '[Looter]', 'Dark Ages'],
                   ['Feodum', '[Four]', '[Victory]', 'Dark Ages'],
                   ['Fortress', '[Four]', '[Action]', 'Dark Ages'],
                   ['Ironmonger', '[Four]', '[Action]', 'Dark Ages'],
                   ['Marauder', '[Four]', '[Attack/Looter]', 'Dark Ages'],
                   ['Procession', '[Four]', '[Action]', 'Dark Ages'],
                   ['Rats', '[Four]', '[Action]', 'Dark Ages'],
                   ['Scavenger', '[Four]', '[Action]', 'Dark Ages'],
                   ['Wandering Minstrel', '[Four]', '[Action]', 'Dark Ages'],
                   ['Band Of Misfits', '[Five]','[Action]', 'Dark Ages'],
                   ['Bandit Camp', '[Five]', '[Action]', 'Dark Ages'],
                   ['Catacombs', '[Five]', '[Action]', 'Dark Ages'],
                   ['Count', '[Five]', '[Action]', 'Dark Ages'],
                   ['Counterfeit', '[Five]', '[Treasure]', 'Dark Ages'],
                   ['Cultist', '[Five]', '[Attack/Looter]', 'Dark Ages'],
                   ['Graverobber', '[Five]', '[Action]', 'Dark Ages'],
                   ['Junk Dealer', '[Five]', '[Action]', 'Dark Ages'],
                   ['Knights', '[Five]', '[Attack/Looter]', 'Dark Ages'],
                   ['Mystic', '[Five]', '[Action]', 'Dark Ages'],
                   ['Pillage', '[Five]', '[Attack]', 'Dark Ages'],
                   ['Rebuild', '[Five]', '[Action]', 'Dark Ages'],
                   ['Rogue', '[Five]', '[Attack]', 'Dark Ages'],
                   ['Altar', '[Six]', '[Action]', 'Dark Ages'],
                   ['Hunting Grounds', '[Six]', '[Action]', 'Dark Ages'],
                   ['Candlestick Maker', '[Two]', '[Action]', 'Guilds'],
                   ['Stonemason', '[Two]', '[Action]', 'Guilds'],
                   ['Doctor', '[Three]', '[Action]', 'Guilds'],
                   ['Masterpiece', '[Three]', '[Treasure]', 'Guilds'],
                   ['Advisor', '[Four]', '[Action]', 'Guilds'],
                   ['Herald', '[Four]', '[Action]', 'Guilds'],
                   ['Plaza', '[Four]', '[Action]', 'Guilds'],
                   ['Taxman', '[Four]', '[Attack]', 'Guilds'],
                   ['Baker', '[Five]', '[Action]', 'Guilds'],
                   ['Butcher', '[Five]', '[Action]', 'Guilds'],
                   ['Journeyman', '[Five]', '[Action]', 'Guilds'],
                   ['Merchant Guild', '[Five]', '[Action]', 'Guilds'],
                   ['Soothsayer', '[Five]', '[Attack]', 'Guilds'],
                   ['Coin Of The Realm', '[Two]', '[Treasure/Reserve]', 'Adventures'],
                   ['Page', '[Two]', '[Traveller]', 'Adventures'],
                   ['Peasant', '[Two]', '[Traveller]', 'Adventures'],
                   ['Ratcatcher', '[Two]', '[Reserve]', 'Adventures'],
                   ['Raze', '[Two]', '[Action]', 'Adventures'],
                   ['Amulet', '[Three]', '[Duration]', 'Adventures'],
                   ['Caravan Guard', '[Three]', '[Reaction/Duration]', 'Adventures'],
                   ['Dungeon', '[Three]', '[Duration]', 'Adventures'],
                   ['Gear', '[Three]', '[Duration]', 'Adventures'],
                   ['Guide', '[Three]', '[Reserve]', 'Adventures'],
                   ['Duplicate', '[Four]', '[Reserve]', 'Adventures'],
                   ['Magpie', '[Four]', '[Action]', 'Adventures'],
                   ['Messenger', '[Four]', '[Action]', 'Adventures'],
                   ['Miser', '[Four]', '[Action]', 'Adventures'],
                   ['Port', '[Four]', '[Action]', 'Adventures'],
                   ['Ranger', '[Four]', '[Action]', 'Adventures'],
                   ['Transmogrify', '[Four]', '[Reserve]', 'Adventures'],
                   ['Artificer', '[Five]', '[Action]', 'Adventures'],
                   ['Bridge Troll', '[Five]', '[Attack/Duration]', 'Adventures'],
                   ['Distant Lands','[Five]', '[Victory/Reserve]', 'Adventures'],
                   ['Giant', '[Five]', '[Attack]', 'Adventures'],
                   ['Haunted Woods', '[Five]', '[Attack/Duration]', 'Adventures'],
                   ['Lost City', '[Five]', '[Action]', 'Adventures'],
                   ['Relic', '[Five]', '[Attack/Treasure]', 'Adventures'],
                   ['Royal Carriage', '[Five]', '[Reserve]', 'Adventures'],
                   ['Storyteller', '[Five]', '[Action]', 'Adventures'],
                   ['Swamp Hag', '[Five]', '[Attack/Duration]', 'Adventures'],
                   ['Treasure Trove', '[Five]', '[Treasure]', 'Adventures'],
                   ['Wine Merchant', '[Five]', '[Reserve]', 'Adventures'],
                   ['Hireling', '[Six]', '[Duration]', 'Adventures'],
                   ['Engineer', '[Four]', '[Action]', 'Empires'],
                   ['City Quarter', '[Eight]', '[Action]', 'Empires'],
                   ['Overlord', '[Eight]', '[Action]', 'Empires'],
                   ['Royal Blacksmith', '[Eight]', '[Action]', 'Empires'],
                   ['Encampment', '[Two]', '[Action]', 'Empires'],
                   ['Plunder', '[Five]', '[Treasure]', 'Empires'],
                   ['Patrician', '[Two]', '[Action]', 'Empires'],
                   ['Emporium', '[Five]', '[Action]', 'Empires'],
                   ['Settlers', '[Two]', '[Action]', 'Empires'],
                   ['Bustling Village', '[Five]', '[Action]', 'Empires'],
                   ['Castles', '[Three]', '[Victory]', 'Empires'],
                   ['Catapult', '[Three]', '[Attack]', 'Empires'],
                   ['Rocks', '[Four]', '[Treasure]', 'Empires'],
                   ['Chariot Race', '[Three]', '[Action]', 'Empires'],
                   ['Enchantress', '[Three]', '[Attack/Duration]', 'Empires'],
                   ["Farmer's Market", '[Three]', '[Gathering]', 'Empires'],
                   ['Gladiator', '[Three]', '[Action]', 'Empires'],
                   ['Fortune', '[Eight]', '[Treasure]', 'Empires'],
                   ['Sacrifice', '[Four]', '[Action]', 'Empires'],
                   ['Temple', '[Four]', '[Gathering]', 'Empires'],
                   ['Villa', '[Four]', '[Action]', 'Empires'],
                   ['Archive', '[Five]', '[Duration]', 'Empires'],
                   ['Capital', '[Five]', '[Treasure]', 'Empires'],
                   ['Charm', '[Five]', '[Treasure]', 'Empires'],
                   ['Crown', '[Five]', '[Action/Treasure]', 'Empires'],
                   ['Forum','[Five]', '[Action]', 'Empires'],
                   ['Groundskeeper', '[Five]', '[Action]', 'Empires'],
                   ['Legionary', '[Five]', '[Attack]', 'Empires'],
                   ['Wild Hunt', '[Five]', '[Gathering]', 'Empires'],
                   ['Druid', '[Two]', '[Fate]', 'Nocturne'],
                   ['Faithful Hound', '[Two]', '[Reaction]', 'Nocturne'],
                   ['Guardian', '[Two]', '[Duration/Night]', 'Nocturne'],
                   ['Monastery', '[Two]', '[Night]', 'Nocturne'],
                   ['Pixie', '[Two]', '[Fate]', 'Nocturne'],
                   ['Tracker', '[Two]', '[Fate]', 'Nocturne'],
                   ['Changeling', '[Three]', '[Night]', 'Nocturne'],
                   ['Fool', '[Three]', '[Fate]', 'Nocturne'],
                   ['Ghost Town', '[Three]', '[Duration/Night]', 'Nocturne'],
                   ['Leprechaun', '[Three]', '[Doom]', 'Nocturne'],
                   ['Night Watchmen', '[Three]', '[Night]', 'Nocturne'],
                   ['Secret Cave', '[Three]', '[Duration]', 'Nocturne'],
                   ['Bard', '[Four]', '[Fate]', 'Nocturne'],
                   ['Blessed Village', '[Four]', '[Fate]', 'Nocturne'],
                   ['Cemetery', '[Four]', '[Victory]', 'Nocturne'],
                   ['Conclave', '[Four]', '[Action]', 'Nocturne'],
                   ["Devil's Workshop", '[Four]', '[Night]', 'Nocturne'],
                   ['Exorcist', '[Four]', '[Night]', 'Nocturne'],
                   ['Necromancer', '[Four]', '[Action]', 'Nocturne'],
                   ['Shepherd', '[Four]', '[Action]', 'Nocturne'],
                   ['Skulk', '[Four]', '[Attack/Doom]', 'Nocturne'],
                   ['Cobbler', '[Five]', '[Duration/Night]', 'Nocturne'],
                   ['Crypt', '[Five]', '[Duration/Night]', 'Nocturne'],
                   ['Cursed Village', '[Five]', '[Doom]', 'Nocturne'],
                   ['Den of Sin', '[Five]', '[Duration/Night]', 'Nocturne'],
                   ['Idol', '[Five]', '[Attack/Treasure/Fate]', 'Nocturne'],
                   ['Pooka', '[Five]', '[Action]', 'Nocturne'],
                   ['Sacred Grove', '[Five]', '[Fate]', 'Nocturne'],
                   ['Tormentor', '[Five]', '[Attack/Doom]', 'Nocturne'],
                   ['Tragic Hero', '[Five]', '[Action]', 'Nocturne'],
                   ['Vampire', '[Five]', '[Attack/Doom]', 'Nocturne'],
                   ['Werewolf', '[Five]', '[Attack/Night/Doom]', 'Nocturne'],
                   ['Raider', '[Six]', '[Attack/Duration/Night]', 'Nocturne'],
                   ['Boarder Guard', '[Two]', '[Action]', 'Renaissance'],
                   ['Ducat', '[Two]', '[Treasure]', 'Renaissance'],
                   ['Lackeys', '[Two]', '[Action]', 'Renaissance'],
                   ['Acting Troupe', '[Three]', '[Action]', 'Renaissance'],
                   ['Cargo Ship', '[Three]', '[Duration]', 'Renaissance'],
                   ['Experiment', '[Three]', '[Action]', 'Renaissance'],
                   ['Improve', '[Three]', '[Action]', 'Renaissance'],
                   ['Flag Bearer', '[Four]', '[Action]', 'Renaissance'],
                   ['Hideout', '[Four]', '[Action]', 'Renaissance'],
                   ['Inventor', '[Four]', '[Action]', 'Renaissance'],
                   ['Mountain Village', '[Four]', '[Action]', 'Renaissance'],
                   ['Patron', '[Four]', '[Reaction]', 'Renaissance'],
                   ['Priest', '[Four]', '[Action]', 'Renaissance'],
                   ['Research', '[Four]', '[Duration]', 'Renaissance'],
                   ['Silk Merchant', '[Four]', '[Action]', 'Renaissance'],
                   ['Old Witch', '[Five]', '[Attack]', 'Renaissance'],
                   ['Recruiter', '[Five]', '[Action]', 'Renaissance'],
                   ['Scepter', '[Five]', '[Treasure]', 'Renaissance'],
                   ['Scholar', '[Five]', '[Action]', 'Renaissance'],
                   ['Sculptor', '[Five]', '[Action]', 'Renaissance'],
                   ['Seer', '[Five]', '[Action]', 'Renaissance'],
                   ['Spices', '[Five]', '[Treasure]', 'Renaissance'],
                   ['Swashbuckler', '[Five]', '[Action]', 'Renaissance'],
                   ['Treasurer', '[Five]', '[Action]', 'Renaissance'],
                   ['Villain', '[Five]', '[Attack]', 'Renaissance'],
                   ['Black Cat', '[Two]', '[Reaction/Attack]', 'Menagerie'],
                   ['Sleigh', '[Two]', '[Reaction]', 'Menagerie'],
                   ['Supplies', '[Two]', '[Treasure]', 'Menagerie'],
                   ['Camel Train', '[Three]', '[Action]', 'Menagerie'],
                   ['Goatherd', '[Three]', '[Action]', 'Menagerie'],
                   ['Scrap', '[Three]', '[Action]', 'Menagerie'],
                   ['Sheepdog', '[Three]', '[Reaction]', 'Menagerie'],
                   ['Snowy Village', '[Three]', '[Action]', 'Menagerie'],
                   ['Stockpile', '[Three]', '[Treasure]', 'Menagerie'],
                   ['Bounty Hunter', '[Four]', '[Action]', 'Menagerie'],
                   ['Cardinal', '[Four]', '[Attack]', 'Menagerie'],
                   ['Cavalry', '[Four]', '[Action]', 'Menagerie'],
                   ['Groom', '[Four]', '[Action]', 'Menagerie'],
                   ['Hostelry', '[Four]', '[Action]', 'Menagerie'],
                   ['Village Green', '[Four]', '[Reaction/Duration]', 'Menagerie'],
                   ['Barge', '[Five]', '[Duration]', 'Menagerie'],
                   ['Coven', '[Five]', '[Attack]','Menagerie'],
                   ['Displace', '[Five]', '[Action]', 'Menagerie'],
                   ['Falconer', '[Five]', '[Reaction]', 'Menagerie'],
                   ['Gatekeeper', '[Five]', '[Attack/Duration]', 'Menagerie'],
                   ['Hunting Lodge', '[Five]', '[Action]', 'Menagerie'],
                   ['Kiln', '[Five]', '[Action]', 'Menagerie'],
                   ['Livery', '[Five]', '[Action]', 'Menagerie'],
                   ['Mastermind', '[Five]', '[Duration]', 'Menagerie'],
                   ['Paddock', '[Five]', '[Action]', 'Menagerie'],
                   ['Sanctuary', '[Five]', '[Action]', 'Menagerie'],
                   ['Fisherman', '[Five]', '[Action]', 'Menagerie'],
                   ['Destrier', '[Six]', '[Action]', 'Menagerie'],
                   ['Wayfarer', '[Six]', '[Action]', 'Menagerie'],
                   ['Animal Fair', '[Seven]', '[Action]', 'Menagerie']
                   ]

